#!/bin/bash

for subDir in *; do
    for file in $subDir/*; do
            if [ -r $file ]; then
                echo $file is readable
            fi

            if [ -w $file ]; then
                echo $file is writable
            fi

            if [ -x $file ]; then
                echo $file is executable
            fi
    done
done
