#!/bin/bash
echo Please enter the two file name

read file1 file2

if [ -f $file1 ] && [ -f $file2 ] && [ $file1 -nt $file2 ]; then
    echo $file1 is newer
elif [ -f $file1 ] && [ -f $file2 ] && [ $file2 -nt $file1 ]; then
    echo $file2 is newer
else
    echo error in files
fi
